In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [11]:
weird = pd.read_csv('HIKARI-CICFlowMeter/zeek/weird-2021-04-16-Friday.log',header=7,sep='\x09')
weird.head()

,time,string,addr,port,addr.1,port.1,string.1,string.2,bool,string.3,string.4
0,1.618589e+09,CdqmHf39pI2DYSCULb,103.255.15.23,37976,10.255.254.228,1514,bad_TCP_checksum,-,F,zeek,TCP
1,1.618589e+09,CdqmHf39pI2DYSCULb,103.255.15.23,37976,10.255.254.228,1514,active_connection_reuse,-,F,zeek,TCP
2,1.618589e+09,CoJ6go3XK0IyZwy6kh,103.255.15.23,35158,8.8.8.8,53,bad_UDP_checksum,-,F,zeek,UDP
3,1.618589e+09,CZVhVa4ypOdOKVPDy,103.255.15.23,6458,34.107.221.82,80,active_connection_reuse,-,F,zeek,TCP
4,1.618589e+09,ChTlId1DrqNUt8MG6f,fe80::c1a7:7791:969e:3c06,58670,2600:1901:0:38d7::,80,bad_TCP_checksum,-,F,zeek,TCP

In [7]:
attack = weird[(weird['addr'] == '103.255.15.23') & (weird['port.1'] == 443) & ((weird['addr.1'] == '128.199.242.104') | (weird['addr.1'] == '128.199.88.81'))].copy()
attack

,time,string,addr,port,addr.1,port.1,string.1,string.2,bool,string.3,string.4
143,1.618589e+09,CgNVr1XvSH6VqnEh4,103.255.15.23,35143,128.199.88.81,443,active_connection_reuse,-,F,zeek,TCP
150,1.618589e+09,CiuuKx3g8ZAbXednJf,103.255.15.23,35143,128.199.88.81,443,above_hole_data_without_any_acks,-,F,zeek,TCP
151,1.618589e+09,CaW8792cu1sQygmE4f,103.255.15.23,7819,128.199.88.81,443,active_connection_reuse,-,F,zeek,TCP
152,1.618589e+09,CKrbtCslv9LTYzcz8,103.255.15.23,47617,128.199.88.81,443,active_connection_reuse,-,F,zeek,TCP
153,1.618589e+09,Cfk9Ub1N8du2k8r4S6,103.255.15.23,48088,128.199.88.81,443,active_connection_reuse,-,F,zeek,TCP
...,...,...,...,...,...,...,...,...,...,...,...
54578,1.618603e+09,C5Z0mN1TzqaoXkwWL2,103.255.15.23,55345,128.199.242.104,443,above_hole_data_without_any_acks,-,F,zeek,TCP
54593,1.618603e+09,CNltlF2L1gNipMWEqg,103.255.15.23,49874,128.199.242.104,443,active_connection_reuse,-,F,zeek,TCP
54596,1.618603e+09,CiRGEW2jFzrDkxA9ci,103.255.15.23,49874,128.199.242.104,443,above_hole_data_without_any_acks,-,F,zeek,TCP
54613,1.618603e+09,CPdH2bX1GDMMKPPF,103.255.15.23,25565,128.199.242.104,443,active_connection_reuse,-,F,zeek,TCP
54620,1.618603e+09,CDN5oJ2EnhmLYFx3uk,103.255.15.23,25565,128.199.242.104,443,above_hole_data_without_any_acks,-,F,zeek,TCP

In [8]:
attack['string.1'].value_counts()

string.1
active_connection_reuse             5472
above_hole_data_without_any_acks    3874
Name: count, dtype: int64

In [10]:
attack['time'] = pd.to_datetime(attack['time'],unit='s')
attack

,time,string,addr,port,addr.1,port.1,string.1,string.2,bool,string.3,string.4
143,2021-04-16 16:08:02.560774144,CgNVr1XvSH6VqnEh4,103.255.15.23,35143,128.199.88.81,443,active_connection_reuse,-,F,zeek,TCP
150,2021-04-16 16:08:06.195168000,CiuuKx3g8ZAbXednJf,103.255.15.23,35143,128.199.88.81,443,above_hole_data_without_any_acks,-,F,zeek,TCP
151,2021-04-16 16:08:06.205025024,CaW8792cu1sQygmE4f,103.255.15.23,7819,128.199.88.81,443,active_connection_reuse,-,F,zeek,TCP
152,2021-04-16 16:08:06.218089216,CKrbtCslv9LTYzcz8,103.255.15.23,47617,128.199.88.81,443,active_connection_reuse,-,F,zeek,TCP
153,2021-04-16 16:08:06.218127104,Cfk9Ub1N8du2k8r4S6,103.255.15.23,48088,128.199.88.81,443,active_connection_reuse,-,F,zeek,TCP
...,...,...,...,...,...,...,...,...,...,...,...
54578,2021-04-16 20:02:51.315293952,C5Z0mN1TzqaoXkwWL2,103.255.15.23,55345,128.199.242.104,443,above_hole_data_without_any_acks,-,F,zeek,TCP
54593,2021-04-16 20:02:59.773183232,CNltlF2L1gNipMWEqg,103.255.15.23,49874,128.199.242.104,443,active_connection_reuse,-,F,zeek,TCP
54596,2021-04-16 20:03:00.435277056,CiRGEW2jFzrDkxA9ci,103.255.15.23,49874,128.199.242.104,443,above_hole_data_without_any_acks,-,F,zeek,TCP
54613,2021-04-16 20:03:09.430202112,CPdH2bX1GDMMKPPF,103.255.15.23,25565,128.199.242.104,443,active_connection_reuse,-,F,zeek,TCP
54620,2021-04-16 20:03:10.098836992,CDN5oJ2EnhmLYFx3uk,103.255.15.23,25565,128.199.242.104,443,above_hole_data_without_any_acks,-,F,zeek,TCP

# analisi bruteforce

In [22]:
file1 = pd.read_csv('HIKARI-CICFlowMeter/zeek/conn-2021-04-11-Sunday.log',header=7,sep='\x09')
file1.head(10)

,time,string,addr,port,addr.1,port.1,enum,string.1,interval,count,count.1,string.2,bool,bool.1,count.2,string.3,count.3,count.4,count.5,count.6,set[string]
0,1.618153e+09,CTSM3xNKS7iYAuhUk,103.255.15.27,37430,103.255.15.23,42001,tcp,-,0.000138,0,0,REJ,F,F,0,Sr,1,60,1,40,-
1,1.618153e+09,CBic7K2bfNLf0h33x9,103.255.15.27,59088,103.255.15.23,42000,tcp,-,0.000126,0,0,REJ,F,F,0,Sr,1,60,1,40,-
2,1.618153e+09,CeYjNh4Ss6gC3Qyho7,103.255.15.27,37438,103.255.15.23,42001,tcp,-,0.000049,0,0,REJ,F,F,0,Sr,1,60,1,40,-
3,1.618153e+09,C2KWST1Ve9L9HkntO1,103.255.15.27,37440,103.255.15.23,42001,tcp,-,0.000097,0,0,REJ,F,F,0,Sr,1,60,1,40,-
4,1.618153e+09,ChAVf41Xob0QuZ4bak,103.255.15.27,59096,103.255.15.23,42000,tcp,-,0.000111,0,0,REJ,F,F,0,Sr,1,60,1,40,-
5,1.618153e+09,CC0QTU31CNb8NJ5fk2,103.255.15.27,59098,103.255.15.23,42000,tcp,-,0.000119,0,0,REJ,F,F,0,Sr,1,60,1,40,-
6,1.618153e+09,CAApmzb4LojdKro8j,103.255.15.27,37448,103.255.15.23,42001,tcp,-,0.000066,0,0,REJ,F,F,0,Sr,1,60,1,40,-
7,1.618153e+09,CRH37U2J6I2kg1kZs3,103.255.15.27,37452,103.255.15.23,42001,tcp,-,0.000134,0,0,REJ,F,F,0,Sr,1,60,1,40,-
8,1.618153e+09,CS8Zdg48Tfb0NRZi3,103.255.15.27,59108,103.255.15.23,42000,tcp,-,0.000136,0,0,REJ,F,F,0,Sr,1,60,1,40,-
9,1.618153e+09,CB5jJt4ZJtrb6lsoyk,103.255.15.27,37458,103.255.15.23,42001,tcp,-,0.000099,0,0,REJ,F,F,0,Sr,1,60,1,40,-

In [37]:
file2 = pd.read_csv('HIKARI-CICFlowMeter/zeek/conn-2021-04-12-Monday.log',header=7,sep='\x09')
file2.head(10)

,time,string,addr,port,addr.1,port.1,enum,string.1,interval,count,count.1,string.2,bool,bool.1,count.2,string.3,count.3,count.4,count.5,count.6,set[string]
0,1.618183e+09,COkIc11N52m65sN55,103.255.15.27,51898,103.255.15.23,42000,tcp,-,0.000147,0,0,REJ,F,F,0,Sr,1,60,1,40,-
1,1.618183e+09,C2Lkv71gjFSYqjZi3h,103.255.15.27,52034,103.255.15.23,42000,tcp,-,0.000157,0,0,REJ,F,F,0,Sr,1,60,1,40,-
2,1.618183e+09,CYWSwtbn0bXrvLsnj,103.255.15.27,58624,103.255.15.23,42001,tcp,-,0.000154,0,0,REJ,F,F,0,Sr,1,60,1,40,-
3,1.618183e+09,CFRZTz1RN1A8BoVoJ1,103.255.15.27,58690,103.255.15.23,42001,tcp,-,0.000151,0,0,REJ,F,F,0,Sr,1,60,1,40,-
4,1.618183e+09,Cd9Vgk2lRVujjwjLta,103.255.15.23,60278,34.107.221.82,80,tcp,-,-,-,-,OTH,F,F,0,C,0,0,0,0,-
5,1.618183e+09,CZhdRZ1VIQrB6KsXrg,103.255.15.23,60282,34.107.221.82,80,tcp,-,-,-,-,OTH,F,F,0,C,0,0,0,0,-
6,1.618183e+09,C481mmjFnULTpTsO1,103.255.15.23,34630,13.227.242.60,443,tcp,-,-,-,-,OTH,F,F,0,C,0,0,0,0,-
7,1.618183e+09,CWf3111a1GLlajGzcl,103.255.15.23,34640,13.227.242.60,443,tcp,-,-,-,-,OTH,F,F,0,C,0,0,0,0,-
8,1.618183e+09,CauXsq45Eqx4FZyNf,103.255.15.27,52358,103.255.15.23,42000,tcp,-,0.000166,0,0,REJ,F,F,0,Sr,1,60,1,40,-
9,1.618183e+09,Crw2vU1iyyxeX5uu3f,103.255.15.27,58950,103.255.15.23,42001,tcp,-,0.000100,0,0,REJ,F,F,0,Sr,1,60,1,40,-

In [23]:
# loading the connection that has perfomed the attack
bf_id = pd.read_csv('bf_id.csv', index_col=0)
bf_id

                                       con_id
0        128.199.88.81-103.255.15.23-443-7819
1       128.199.88.81-103.255.15.23-443-48088
2       128.199.88.81-103.255.15.23-443-47617
3        128.199.88.81-103.255.15.23-443-4961
4       128.199.88.81-103.255.15.23-443-47284
...                                       ...
5878  128.199.242.104-103.255.15.23-443-18417
5879   128.199.242.104-103.255.15.23-443-2742
5880  128.199.242.104-103.255.15.23-443-39506
5881  128.199.242.104-103.255.15.23-443-47432
5882  128.199.242.104-103.255.15.23-443-12029

[5883 rows x 1 columns]

In [32]:
file1['con_id'] = file1['addr.1'] + '-' + file1['addr'] + '-' + file1['port.1'].astype('str') + '-' + file1['port'].astype('str')
file1['con_id']

0           103.255.15.23-103.255.15.27-42001-37430
1           103.255.15.23-103.255.15.27-42000-59088
2           103.255.15.23-103.255.15.27-42001-37438
3           103.255.15.23-103.255.15.27-42001-37440
4           103.255.15.23-103.255.15.27-42000-59096
                            ...
26570         74.125.24.149-103.255.15.23-443-13990
26571      255.255.255.255-103.255.15.203-5678-5678
26572      255.255.255.255-103.255.15.20-1947-63061
26573       103.255.15.255-103.255.15.20-1947-63061
26574    255.255.255.255-103.255.15.164-10670-10669
Name: con_id, Length: 26575, dtype: object

In [38]:
file2['con_id'] = file2['addr.1'] + '-' + file2['addr'] + '-' + file2['port.1'].astype('str') + '-' + file2['port'].astype('str')
file2['con_id']

0         103.255.15.23-103.255.15.27-42000-51898
1         103.255.15.23-103.255.15.27-42000-52034
2         103.255.15.23-103.255.15.27-42001-58624
3         103.255.15.23-103.255.15.27-42001-58690
4            34.107.221.82-103.255.15.23-80-60278
                           ...
18778     103.255.15.255-103.255.15.20-1947-63061
18779    255.255.255.255-103.255.15.20-1947-63061
18780      87.250.250.119-103.255.15.23-443-64570
18781      93.158.134.119-103.255.15.23-443-11393
18782       87.250.251.119-103.255.15.23-443-9080
Name: con_id, Length: 18783, dtype: object

In [39]:
# creating a function to label the connection
con_id_list = bf_id['con_id'].to_list()

def label_connection(flow_id):
    if flow_id in con_id_list:
        return 'Bruteforce'
    else:
        return 'Benign'

file1['Label'] = file1['con_id'].apply(label_connection)
file2['Label'] = file2['con_id'].apply(label_connection)

In [35]:
file1['Label'].value_counts()

Label
Benign        25773
Bruteforce      802
Name: count, dtype: int64

In [40]:
file2['Label'].value_counts()

Label
Benign        18731
Bruteforce       52
Name: count, dtype: int64